version: "3.4"
services:
  cms_dormitory:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 80
    ports:
      - 80:80
    environment:
      - CHOKIDAR_USEPOLLING=true
